[build]
  base    = "web"
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200